
apiVersion: v1
kind: Service
metadata:
  name: blog-app
  namespace: default
  labels:
    component: blog-app
spec:
  ports:
  - name: http-blog-app
    port: 9999
  selector:
    component: blog-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-app
  namespace: default
  labels:
    component: blog-app
spec:
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      labels:
        component: blog-app
    spec:
      containers:
      - image: rock1017/blog-app:latest
        name: blog-app