---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-gen-config
  namespace: default
  labels:
    component: data-gen-config
data:
  data-gen-config.json: |
    {
        "topology" : {
            "services" : [
            {
                "serviceName" : "frontend",
                "instances" : [ "frontend-6b654dbf57-zq8dt", "frontend-d847fdcf5-j6s2f", "frontend-79d8c8d6c8-9sbff" ],
                "tagSets" : [
                { "weight": 1, "tags": { "version" : "v127", "region" : "us-east-1" }},
                { "weight": 1, "tags": { "version" : "v125", "region" : "us-east-1" }},
                { "weight": 2, "tags": { "version" : "v125", "region" : "us-west-1" }}
                ],
                "routes" : [
                {
                    "route" : "/product",
                    "downstreamCalls" : { "productcatalogservice" : "/GetProducts", "recommendationservice" : "/GetRecommendations", "adservice" : "/AdRequest" },
                    "maxLatencyMillis": 200,
                    "tagSets": [
                    { "weight": 1, "tags": { "starter" : "charmander"}, "tagGenerators":  [{"numTags":  50, "numVals":  3000, "valLength": 16}]},
                    { "weight": 1, "tags": { "starter" : "squirtle"}},
                    { "weight": 1, "tags": { "starter" : "bulbasaur"}}
                    ]
                },
                {
                    "route" : "/cart",
                    "downstreamCalls" : { "cartservice" : "/GetCart", "recommendationservice" : "/GetRecommendations" },
                    "maxLatencyMillis" : 100
                },
                {
                    "route" : "/checkout",
                    "downstreamCalls" : { "checkoutservice" : "/PlaceOrder" },
                    "maxLatencyMillis" : 800
                },
                {
                    "route" : "/shipping",
                    "downstreamCalls" : { "shippingservice" : "/GetQuote" },
                    "maxLatencyMillis" : 50
                },
                {
                    "route" : "/currency",
                    "downstreamCalls" : { "currencyservice" : "/GetConversion" },
                    "maxLatencyMillis" : 50
                }
                ]
            },
            {
                "serviceName" : "productcatalogservice",
                "instances" : [ "productcatalogservice-6b654dbf57-zq8dt", "productcatalogservice-d847fdcf5-j6s2f" ],
                "tagSets" : [{"tags": { "version" : "v52"}, "inherit":  ["region"]}],
                "routes" : [
                {
                    "route" : "/GetProducts",
                    "downstreamCalls" : { },
                    "maxLatencyMillis" : 100,
                    "tagSets": [
                    {"inherit": ["starter"]}
                    ]
                },
                {
                    "route" : "/SearchProducts",
                    "downstreamCalls" : { },
                    "tagSets" : [
                    {"weight": 15, "tags": { "error" : true, "http.status_code":  503}},
                    {"weight": 85, "tags":  {}}
                    ],
                    "maxLatencyMillis" : 400
                }
                ]
            },
            {
                "serviceName" : "recommendationservice",
                "instances" : [ "recommendationservice-6b654dbf57-zq8dt", "recommendationservice-d847fdcf5-j6s2f" ],
                "tagSets" : [{"tags" : { "version" : "v234", "region" : "us-east-1" }}],
                "routes" : [
                {
                    "route" : "/GetRecommendations",
                    "downstreamCalls" : { "productcatalogservice" : "/GetProducts" },
                    "maxLatencyMillis" : 200
                }
                ]
            },
            {
                "serviceName" : "cartservice",
                "instances" : [ "cartservice-6b654dbf57-zq8dt", "cartservice-d847fdcf5-j6s2f" ],
                "tagSets": [{"tags" : { "version" : "v5", "region" : "us-east-1" }}],
                "routes" : [
                {
                    "route" : "/GetCart",
                    "downstreamCalls" : { },
                    "maxLatencyMillis" : 200
                }
                ]
            },
            {
                "serviceName" : "checkoutservice",
                "instances" : [ "checkoutservice-6b654dbf57-zq8dt", "checkoutservice-d847fdcf5-j6s2f" ],
                "tagSets": [{"tags" : { "version" : "v37", "region" : "us-east-1" }}],
                "routes" : [
                {
                    "route" : "/PlaceOrder",
                    "downstreamCalls" : { "paymentservice" : "/CreditCardInfo", "shippingservice" : "/Address", "currencyservice" : "/GetConversion", "cartservice" : "/GetCart", "emailservice" : "/SendOrderConfirmation" },
                    "tagSets" : [
                    {"weight": 25, "tags": { "error" : true, "http.status_code":  503}},
                    {"weight": 85, "tags":  {}}
                    ],
                    "maxLatencyMillis" : 500
                }
                ]
            },
            {
                "serviceName" : "paymentservice",
                "instances" : [ "paymentservice-6b654dbf57-zq8dt", "paymentservice-d847fdcf5-j6s2f" ],
                "tagSets": [{"tags" : { "version" : "v177", "region" : "us-east-1" }}],
                "routes" : [
                {
                    "route" : "/ChargeRequest",
                    "downstreamCalls" : { "paymentservice" : "/CreditCardInfo" },
                    "maxLatencyMillis" : 700
                },
                {
                    "route" : "/CreditCardInfo",
                    "downstreamCalls" : { },
                    "maxLatencyMillis" : 50
                }
                ]
            },
            {
                "serviceName" : "shippingservice",
                "instances" : [ "shippingservice-6b654dbf57-zq8dt", "shippingservice-d847fdcf5-j6s2f" ],
                "tagSets": [{"tags" : { "version" : "v127", "region" : "us-east-1" }}],
                "routes" : [
                {
                    "route" : "/GetQuote",
                    "downstreamCalls" : { "shippingservice" : "/Address" },
                    "maxLatencyMillis" : 250
                },
                {
                    "route" : "/ShipOrder",
                    "downstreamCalls" : { "shippingservice" : "/Address"},
                    "maxLatencyMillis" : 500
                },
                {
                    "route" : "/Address",
                    "downstreamCalls" : { },
                    "maxLatencyMillis" : 100
                }
                ]
            },
            {
                "serviceName" : "emailservice",
                "instances" : [ "emailservice-6b654dbf57-zq8dt", "emailservice-d847fdcf5-j6s2f" ],
                "tagSets": [{"tags" : { "version" : "v27", "region" : "us-east-1" }}],
                "routes" : [
                {
                    "route" : "/SendOrderConfirmation",
                    "downstreamCalls" : { "emailservice" : "/OrderResult" },
                    "tagSets" : [
                    {"weight": 15, "tags": { "error" : true, "http.status_code":  503}},
                    {"weight": 85, "tags":  {}}
                    ],
                    "maxLatencyMillis" : 500
                },
                {
                    "route" : "/OrderResult",
                    "downstreamCalls" : { },
                    "maxLatencyMillis" : 100
                }
                ]
            },
            {
                "serviceName" : "currencyservice",
                "instances" : [ "currencyservice-6b654dbf57-zq8dt", "currencyservice-d847fdcf5-j6s2f" ],
                "tagSets": [{"tags" : { "version" : "v27", "region" : "us-east-1" }}],
                "routes" : [
                {
                    "route" : "/GetConversion",
                    "downstreamCalls" : { "currencyservice" : "/Money" },
                    "maxLatencyMillis" : 100
                },
                {
                    "route" : "/Money",
                    "downstreamCalls" : { },
                    "maxLatencyMillis" : 100
                }
                ]
            },
            {
                "serviceName" : "adservice",
                "instances" : [ "adservice-6b654dbf57-zq8dt", "adservice-d847fdcf5-j6s2f" ],
                "tagSets" : [{ "version" : "v37", "region" : "us-east-1" }],
                "routes" : [
                {
                    "route" : "/AdRequest",
                    "downstreamCalls" : { },
                    "maxLatencyMillis" : 500
                },
                {
                    "route" : "/Ad",
                    "downstreamCalls" : { },
                    "maxLatencyMillis" : 500
                }
                ]
            }
            ]
        },
        "rootRoutes" : [
            {
            "service" : "frontend",
            "route" : "/product",
            "tracesPerHour" : 2880
            },
            {
            "service" : "frontend",
            "route" : "/cart",
            "tracesPerHour" : 14400
            },
            {
            "service" : "frontend",
            "route" : "/shipping",
            "tracesPerHour" : 480
            },
            {
            "service" : "frontend",
            "route" : "/currency",
            "tracesPerHour" : 200
            },
            {
            "service" : "frontend",
            "route" : "/checkout",
            "tracesPerHour" : 480
            }
        ]
        }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-gen
  namespace: default
  labels:
    component: data-gen
spec:
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      labels:
        component: data-gen
    spec:
      containers:
      - command:
          - "/opt/omnition/start.sh"
        env:
        - name: JAEGER_COLLECTOR_URL
          value: "http://otel-collector:14268"
        - name: TOPOLOGY_FILE
          value: "/opt/omnition/topologies/hipster-shop.json"
        image: rock1017/synthetic-load-generator:latest
        name: data-gen
        resources:
          limits:
            cpu: 1
            #memory: 2Gi
          requests:
            cpu: 200m
            # memory: 400Mi
        volumeMounts:
        - name: data-gen-config
          mountPath: /opt/omnition/topologies/custom
      volumes:
        - configMap:
            name: data-gen-config
            items:
              - key: data-gen-config.json
                path: data-gen-config.json
          name: data-gen-config