
apiVersion: v1
kind: Service
metadata:
  name: prom-data-gen
  namespace: default
  labels:
    component: prom-data-gen
spec:
  ports:
  - name: prometheus
    port: 8888
  selector:
    component: prom-data-gen
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom-data-gen
  namespace: default
  labels:
    component: prom-data-gen
spec:
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      labels:
        component: prom-data-gen
    spec:
      containers:
        - image: rock1017/prom-fake-gen:latest
          name: prom-data-gen
          ports:
          - containerPort: 8888